apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    trustDomainAliases: ["{{GKE_PROJECT_ID}}.svc.id.goog"]
kind: ConfigMap
metadata:
  name: istio-asm-managed
  namespace: istio-system
