kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding
subjects:
- kind: Group
  name: "team-name@nickeberts.altostrat.com"
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io  