# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-frontend
  template:
    metadata:
      labels:
        app: prometheus-frontend
    spec:
      automountServiceAccountToken: true
      # nodeSelector:
      #   kubernetes.io/os: linux
      #   kubernetes.io/arch: amd64
      containers:
      - name: frontend
        image: "gke.gcr.io/prometheus-engine/frontend:v0.4.1-gke.0"
        args:
        - "--web.listen-address=:9090"
        - "--query.project-id={{GKE_PROJECT_ID}}"
        ports:
        - name: web
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
spec:
  clusterIP: None
  selector:
    app: prometheus-frontend
  ports:
  - name: web
    port: 9090
