apiVersion: v1
kind: Service
metadata:
  name: canary
  annotations:
    configmanagement.gke.io/cluster-selector: selector-prod
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: app-name