apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: asm-ingress-xlb-config
  namespace: asm-gateways
  annotations:
    configmanagement.gke.io/cluster-selector: selector-controller
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP