apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-deployment
  namespace: asm-gateways
  annotations:
    configmanagement.gke.io/cluster-selector: selector-controller
  labels:
    app: load-test
spec:
  selector:
    matchLabels:
      app: load-test
  template:
    metadata:
      labels:
        app: load-test
    spec:
      containers:
      - name: load-tester
        image: argoproj/load-tester:latest
        command: [sh, -c, -x, -e]
        args:
        - |
          wrk -t10 -c40 -d6h -s report.lua https://rollout-demo.endpoints.fleets-acm-demo00.cloud.goog/
          jq -e '.errors_ratio <= 0.05 and .latency_avg_ms < 100' report.json