apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    multicluster_mode: connected
    trustDomainAliases: ["{{GKE_PROJECT_ID}}.svc.id.goog"]
kind: ConfigMap
metadata:
  name: istio-asm-managed
  namespace: istio-system
---
apiVersion: v1
data:
kind: ConfigMap
metadata:
  name: asm-options
  namespace: istio-system
