apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: TEAM_NAME-APP_NAME-wave-1-generator
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
          matchExpressions:
          - key: wave
            operator: In
            values: ["one"]
  template:
    metadata:
      name: '{{name}}-TEAM_NAME-APP_NAME'
    spec:
      project: "TEAM_NAME"
      source:
        repoURL: {{SYNC_REPO}}
        targetRevision: "wave-one"
        path: teams/TEAM_NAME/APP_NAME
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: APP_NAME
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 20
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
