# GKE PoC Toolkit config
terraformState: cloud  
clustersProjectId: "my-project"
governanceProjectId: "my-project"
region: "us-central1"
enablePreemptibleNodepool: false # Enforced on Linux Node pools only
enableWindowsNodepool: false
privateEndpoint: false
configSync: true 
policyController: true
releaseChannel: REGULAR
defaultNodepoolOS: cos
initialNodeCount: 3
maxNodeCount: 10
minNodeCount: 3
multiClusterGateway: false
anthosServiceMesh: false
tfModuleRepo: "github.com/GoogleCloudPlatform/gke-poc-toolkit//terraform/modules/"
tfModuleBranch: "main"
sendAnalytics: true
vpcConfig:
  vpcName: "default"
  vpcType: "standalone" 
  vpcProjectId: "my-project" 
  podCIDRName: "default"
  svcCIDRName: "default"
  authCIDR: "0.0.0.0/0"
clustersConfig:   
- clusterName: "gke-central"
  machineType: "e2-standard-4"
  region: "us-central1"
  zone: "us-central1-a"  
  subnetName: "us-central1"
