apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.2/manifests/ha/install.yaml
- argocd-server-backend-config.yaml
- argocd-server-frontend-config.yaml
- argocd-server-ingress.yaml
- argocd-namespace.yaml
- argocd-managed-cert.yaml

patchesStrategicMerge:
- argocd-server-deployment_patch.yaml
- argocd-server-svc_patch.yaml
- argocd-sa.yaml
