kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: selector-us-central1
spec:
  selector:
    matchExpressions:
      - key: location
        operator: In
        values:
        - "us-central1"