kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: selector-controller
spec:
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values:
        - "controller"