apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mcc-clusters-config-generator
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: {{SYNC_REPO}}
              revision: HEAD
              directories:
                - path: multi-cluster-controllers/*
          - clusters:
              selector:
                matchLabels:
                  env: "multi-cluster-controller"
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: "admin"
      source:
        repoURL: {{SYNC_REPO}}
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}' # 'server' field of the secret
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        retry:
          limit: 20
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
