apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-1
namePrefix: app-1-
resources:
- ../../../app-template/base/
- namespace.yaml
- rollout.yaml
commonLabels:
  app: app-1
patches:
- patch.yaml