apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whereami
namePrefix: whereami-
resources:
- ../../../app-template/base/
- namespace.yaml
- rollout.yaml
commonLabels:
  app: whereami
patches:
- patch.yaml