apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
subjects:
- kind: Group
  name: "team-1@nickeberts.altostrat.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice
spec:
  gateways:
  - asm-gateways/asm-ingress-gateway-xlb
  hosts:
  - whereami.endpoints.argo-sp.cloud.goog
  http:
  - name: primary
    route:
    - destination:
        host: whereami-stable
        port:
          number: 80
      weight: 100
    - destination:
        host: whereami-canary
        port:
          number: 80
      weight: 0