apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: whereami-canary
      stableService: whereami-stable
      trafficRouting:
        istio:
          virtualServices:
          - name: whereami-virtualservice # At least one virtualService is required
            routes:
            - primary # At least one route is required
      steps:
      - setWeight: 20
      - pause:
          duration: 4m
      - analysis:
          templates:
          - templateName: success-rate
            clusterScope: true
          args:
          - name: service-name
            value: whereami-canary.team-1-whereami.svc.cluster.local
      - setWeight: 80
      - pause:
          duration: 4m
      - analysis:
          templates:
          - templateName: success-rate
            clusterScope: true
          args:
          - name: service-name
            value: whereami-canary.team-1-whereami.svc.cluster.local
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
        istio-injection: enabled
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.2.6
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m